title: "பாண்டியராஜா சங்க இலக்கியத் தொடரடைவு "
description: "இங்கு சங்க இலக்கியங்களின் பயன் படுத்தப் பட்டு உள்ள சொற்களின் பட்டியலை தரவிறக்கம் செய்து கொள்ளலாம். மேலும் ஏதேனும் புதிய ஆய்வுகளை மேற்கொண்டு தமிழை மென்மேலும் செழுமை யடைய உதவிடலாம்"
show_downloads: true
google_analytics: "ua-119554313-1"
theme: jekyll-theme-cayman